# Generated by Django 4.2 on 2024-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_reservation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='facilities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
