# Generated by Django 4.2.11 on 2024-05-26 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0009_message"),
    ]

    operations = [
        migrations.RenameModel(old_name="Message", new_name="Chats",),
    ]
