# Generated by Django 4.2.11 on 2024-06-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_salereport_reservation_facilities"),
    ]

    operations = [
        migrations.DeleteModel(name="SaleReport",),
    ]
